exe_path = "C:\\Users\\HP\\driver\\chromedriver.exe"
url = "http://localhost:8080/ui/"
user_name = "admin"
psw = "qwerty"
project_name = "CLM Template"
xpsubmit = "//input[@type='submit']"
xpun = "//input[@name='login']"
xppsw = "//input[@name='password']"
xpprj = "//input[@name='project']"
xp_frame_parent = "//iframe[@name='frameset']"
xp_frame_maincontent = "//iframe[@id='mainContentIframe']"
xp_frame_create_edit = "//iframe[@data-title='Create/edit Field']"
xp_frame_top_info = "//iframe[@name='top_info']"
xp_home = "//a[@data-shortcut='HOME'][contains(text(),'Home')]"
xp_bento = "//div[@class='navItem bento']"
xp_bento_box = "//div[@class='menu-panel navigation-menu bento-menu-navigation js_f0tn_quick']"
xp_contract_manage = "//div[@class='bento-menu-content']//div[contains(text(),'Contract Management')]/.."
xp_contracts = "//div[@id='tableInfo']//small[contains(text(),'Contracts')]"
xp_contracts_dd = "//div[@id='topNavBar']//a[contains(text(),'Contracts')]/following-sibling::*[1]"
xp_setup_contract = "//span[text()='Setup Contracts']/../.."
xp_fields = "//div[text()='Fields']"
xp_edit_create_approval = "//td[text()='Button: Create Approvals']/preceding-sibling::*[1]"
xp_dialog_box = "//dialog[@role='topdialog']"
xp_execute_action_list = "//div[contains(text(),'Create Approval Actions')]/../../../tr"
xp_wait_msg_ele = "//div[contains(text(),'-- Wait for Completion --')]"
xp_add_wait = "//input[@value='Add Wait Point']"
xp_finish = "//input[@value='Finish']"
xp_for_item_at_2nd_position = "//div[contains(text(),'Create Approval Actions')]/../../../tr[2]//div"
xp_contract_top_nav = "//a[text()='Contracts']/.."
xp_new = "//a[@title='New']"
xp_contract_type = "//select[@name='contract_type_$sel']"
xp_contract_title = "//input[@name='contract_title1']"
xp_contract_disc = "//textarea[@name='contract_description']"
xp_save_dd = "//button[@id='$finishMenuOpen1']"
xp_save_continue = "//span[text()='Save & Continue']/.."
xp_approval = "//div[@title='Approvals']"
xp_table_header = "//div[@id='related1381327352520.content_header']"
xp_number_of_approval_nneded = "//td[@id='number_of_approvals_needed_calc_field_result']"
xp_create_approval = "//input[@value='Create Approvals']"
xp_launch_approval = "//input[@value='Launch Approval Process']"
xp_clk_profile = "//div[@id='tm-profile']"
xp_clk_logout = "//span[text()='Logout']/.."
msg_expected = "-- Wait for Completion --"